run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - nilerr
    - errorlint
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/raphaeltorquat0/iptuapi-go
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # Audit errors not checked (we handle this explicitly)
      - G304 # File path provided as taint input (false positives in tests)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: _test\.go
      text: "G404" # Weak random number generator
  max-issues-per-linter: 0
  max-same-issues: 0
